=== minvws/nl-covid19-data-dashboard/web/schema/ranges/__index.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "title": "ranges",
  "required": [
    "last_generated",
    "proto_name",
    "name",
    "code",
    "min_max_values"
  ],
  "additionalProperties": false,
  "properties": {
    "last_generated": {
      "type": "string"
    },
    "proto_name": {
      "type": "string",
      "enum": ["RANGES"]
    },
    "name": {
      "type": "string",
      "enum": ["ranges"]
    },
    "code": {
      "type": "string",
      "enum": ["ra"]
    },
    "min_max_values": {
      "$ref": "min_max_values.json"
    }
  }
}

=== minvws/nl-covid19-data-dashboard/src/pages-tests/fixtures/RANGES.json
{
  "last_generated": "1606230700",
  "proto_name": "RANGES",
  "name": "ranges",
  "code": "ra",
  "min_max_values": {
    "values": [
      {
        "date_of_report_unix": 1606230700,
        "max_moving_average_hospital": 597.3,
        "min_moving_average_hospital": 0.3,
        "max_incidentie": 119.6,
        "min_incidentie": 5.7,
        "max_infectious_normalized_low": 729.1,
        "min_infectious_normalized_low": 3.0,
        "max_infectious_normalized_avg": 970.4,
        "min_infectious_normalized_avg": 0.0,
        "max_infectious_normalized_high": 1210.5,
        "min_infectious_normalized_high": 8.3,
        "max_infectious_low": 126916,
        "min_infectious_low": 518,
        "max_infectious_avg": 168925,
        "min_infectious_avg": 0,
        "max_infectious_high": 210712,
        "min_infectious_high": 1438,
        "max_infected_daily_total": 11091,
        "min_infected_daily_total": 4,
        "max_total_reported_increase_per_region": 1294.0,
        "min_total_reported_increase_per_region": 0.0,
        "max_infected_total_counts_per_region": 4475.1,
        "min_infected_total_counts_per_region": 1.9,
        "max_hospital_total_counts_per_region": 1866.0,
        "min_hospital_total_counts_per_region": 0.0,
        "max_infected_increase_per_region": 121.9,
        "min_infected_increase_per_region": 0.0,
        "max_hospital_increase_per_region": 220.0,
        "min_hospital_increase_per_region": 0.0,
        "max_hospital_moving_avg_per_region": 102.0,
        "min_hospital_moving_avg_per_region": 0.0,
        "max_reproduction_index_low": 1.65,
        "min_reproduction_index_low": 0.0,
        "max_reproduction_index_avg": 2.2,
        "min_reproduction_index_avg": 0.0,
        "max_reproduction_index_high": 5.0,
        "min_reproduction_index_high": 0.0,
        "max_moving_average_ic": 110.3,
        "min_moving_average_ic": 0.0,
        "max_infected_daily_increase": 63.7,
        "min_infected_daily_increase": 0.0,
        "max_deceased_nursery_daily": 85,
        "min_deceased_nursery_daily": 0,
        "max_infected_nursery_daily": 285,
        "min_infected_nursery_daily": 0,
        "max_total_reported_locations": 828,
        "min_total_reported_locations": 0,
        "max_total_new_reported_locations": 64,
        "min_total_new_reported_locations": 0,
        "max_average": 719.38,
        "min_average": 46.36,
        "max_latest_rna_normalized": 7538.35,
        "min_latest_rna_normalized": 0.0,
        "max_average_per_region": 2403.6,
        "min_average_per_region": 11.25,
        "max_rna_normalized": 17132.6,
        "min_rna_normalized": 0.0
      }
    ],
    "last_value": {
      "date_of_report_unix": 1606230700,
      "max_moving_average_hospital": 597.3,
      "min_moving_average_hospital": 0.3,
      "max_incidentie": 119.6,
      "min_incidentie": 5.7,
      "max_infectious_normalized_low": 729.1,
      "min_infectious_normalized_low": 3.0,
      "max_infectious_normalized_avg": 970.4,
      "min_infectious_normalized_avg": 0.0,
      "max_infectious_normalized_high": 1210.5,
      "min_infectious_normalized_high": 8.3,
      "max_infectious_low": 126916,
      "min_infectious_low": 518,
      "max_infectious_avg": 168925,
      "min_infectious_avg": 0,
      "max_infectious_high": 210712,
      "min_infectious_high": 1438,
      "max_infected_daily_total": 11091,
      "min_infected_daily_total": 4,
      "max_total_reported_increase_per_region": 1294.0,
      "min_total_reported_increase_per_region": 0.0,
      "max_infected_total_counts_per_region": 4475.1,
      "min_infected_total_counts_per_region": 1.9,
      "max_hospital_total_counts_per_region": 1866.0,
      "min_hospital_total_counts_per_region": 0.0,
      "max_infected_increase_per_region": 121.9,
      "min_infected_increase_per_region": 0.0,
      "max_hospital_increase_per_region": 220.0,
      "min_hospital_increase_per_region": 0.0,
      "max_hospital_moving_avg_per_region": 102.0,
      "min_hospital_moving_avg_per_region": 0.0,
      "max_reproduction_index_low": 1.65,
      "min_reproduction_index_low": 0.0,
      "max_reproduction_index_avg": 2.2,
      "min_reproduction_index_avg": 0.0,
      "max_reproduction_index_high": 5.0,
      "min_reproduction_index_high": 0.0,
      "max_moving_average_ic": 110.3,
      "min_moving_average_ic": 0.0,
      "max_infected_daily_increase": 63.7,
      "min_infected_daily_increase": 0.0,
      "max_deceased_nursery_daily": 85,
      "min_deceased_nursery_daily": 0,
      "max_infected_nursery_daily": 285,
      "min_infected_nursery_daily": 0,
      "max_total_reported_locations": 828,
      "min_total_reported_locations": 0,
      "max_total_new_reported_locations": 64,
      "min_total_new_reported_locations": 0,
      "max_average": 719.38,
      "min_average": 46.36,
      "max_latest_rna_normalized": 7538.35,
      "min_latest_rna_normalized": 0.0,
      "max_average_per_region": 2403.6,
      "min_average_per_region": 11.25,
      "max_rna_normalized": 17132.6,
      "min_rna_normalized": 0.0
    }
  }
}
