=== minvws/nl-covid19-data-dashboard/schema/municipal/__index.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "title": "municipal",
  "additionalProperties": false,
  "required": [
    "last_generated",
    "proto_name",
    "name",
    "code",
    "hospital_admissions",
    "positive_tested_people"
  ],
  "properties": {
    "last_generated": {
      "type": "string"
    },
    "proto_name": {
      "type": "string",
      "pattern": "^GM[0-9]+$"
    },
    "name": {
      "type": "string",
      "pattern": "^GM[0-9]+$"
    },
    "code": {
      "type": "string",
      "pattern": "^GM[0-9]+$"
    },
    "hospital_admissions": {
      "$ref": "hospital_admissions.json"
    },
    "positive_tested_people": {
      "$ref": "positive_tested_people.json"
    },
    "sewer_measurements": {
      "$ref": "sewer_measurements.json"
    },
    "results_per_sewer_installation_per_municipality": {
      "$ref": "results_per_sewer_installation_per_municipality.json"
    }
  }
}

=== minvws/nl-covid19-data-dashboard/src/pages-tests/fixtures/GM1724.json
{
  "last_generated": "1605606390",
  "proto_name": "GM1724",
  "name": "GM1724",
  "code": "GM1724",
  "hospital_admissions": {
    "values": [
      {
        "date_of_report_unix": 1584316800,
        "gmcode": "GM1724",
        "municipality_name": "Bergeijk",
        "moving_average_hospital": 0.0,
        "date_of_insertion_unix": 1605169739
      },
      {
        "date_of_report_unix": 1584403200,
        "gmcode": "GM1724",
        "municipality_name": "Bergeijk",
        "moving_average_hospital": 0.0,
        "date_of_insertion_unix": 1605169739
      },
      {
        "date_of_report_unix": 1584489600,
        "gmcode": "GM1724",
        "municipality_name": "Bergeijk",
        "moving_average_hospital": 0.0,
        "date_of_insertion_unix": 1605169739
      },
      {
        "date_of_report_unix": 1584576000,
        "gmcode": "GM1724",
        "municipality_name": "Bergeijk",
        "moving_average_hospital": 0.0,
        "date_of_insertion_unix": 1605169739
      },
      {
        "date_of_report_unix": 1584662400,
        "gmcode": "GM1724",
        "municipality_name": "Bergeijk",
        "moving_average_hospital": 0.0,
        "date_of_insertion_unix": 1605169739
      },
      {
        "date_of_report_unix": 1584748800,
        "gmcode": "GM1724",
        "municipality_name": "Bergeijk",
        "moving_average_hospital": 0.0,
        "date_of_insertion_unix": 1605169739
      },
      {
        "date_of_report_unix": 1584835200,
        "gmcode": "GM1724",
        "municipality_name": "Bergeijk",
        "moving_average_hospital": 0.0,
        "date_of_insertion_unix": 1605169739
      },
      {
        "date_of_report_unix": 1584921600,
        "gmcode": "GM1724",
        "municipality_name": "Bergeijk",
        "moving_average_hospital": 0.0,
        "date_of_insertion_unix": 1605169739
      },
      {
        "date_of_report_unix": 1585008000,
        "gmcode": "GM1724",
        "municipality_name": "Bergeijk",
        "moving_average_hospital": 0.0,
        "date_of_insertion_unix": 1605169739
      },
      {
        "date_of_report_unix": 1585094400,
        "gmcode": "GM1724",
        "municipality_name": "Bergeijk",
        "moving_average_hospital": 0.0,
        "date_of_insertion_unix": 1605169739
      },
      {
        "date_of_report_unix": 1585180800,
        "gmcode": "GM1724",
        "municipality_name": "Bergeijk",
        "moving_average_hospital": 0.0,
        "date_of_insertion_unix": 1605169739
      },
      {
        "date_of_report_unix": 1585267200,
        "gmcode": "GM1724",
        "municipality_name": "Bergeijk",
        "moving_average_hospital": 0.0,
        "date_of_insertion_unix": 1605169739
      },
      {
        "date_of_report_unix": 1585353600,
        "gmcode": "GM1724",
        "municipality_name": "Bergeijk",
        "moving_average_hospital": 0.0,
        "date_of_insertion_unix": 1605169739
      },
      {
        "date_of_report_unix": 1585440000,
        "gmcode": "GM1724",
        "municipality_name": "Bergeijk",
        "moving_average_hospital": 0.7,
        "date_of_insertion_unix": 1605169739
      },
      {
        "date_of_report_unix": 1585526400,
        "gmcode": "GM1724",
        "municipality_name": "Bergeijk",
        "moving_average_hospital": 1.3,
        "date_of_insertion_unix": 1605169739
      },
      {
        "date_of_report_unix": 1585612800,
        "gmcode": "GM1724",
        "municipality_name": "Bergeijk",
        "moving_average_hospital": 1.7,
        "date_of_insertion_unix": 1605169739
      },
      {
        "date_of_report_unix": 1585699200,
        "gmcode": "GM1724",
        "municipality_name": "Bergeijk",
        "moving_average_hospital": 1.0,
        "date_of_insertion_unix": 1605169739
      },
      {
        "date_of_report_unix": 1585785600,
        "gmcode": "GM1724",
        "municipality_name": "Bergeijk",
        "moving_average_hospital": 0.3,
        "date_of_insertion_unix": 1605169739
      },
      {
        "date_of_report_unix": 1585872000,
        "gmcode": "GM1724",
        "municipality_name": "Bergeijk",
        "moving_average_hospital": 0.7,
        "date_of_insertion_unix": 1605169739
      },
      {
        "date_of_report_unix": 1585958400,
        "gmcode": "GM1724",
        "municipality_name": "Bergeijk",
        "moving_average_hospital": 1.3,
        "date_of_insertion_unix": 1605169739
      },
      {
        "date_of_report_unix": 1586044800,
        "gmcode": "GM1724",
        "municipality_name": "Bergeijk",
        "moving_average_hospital": 1.3,
        "date_of_insertion_unix": 1605169739
      },
      {
        "date_of_report_unix": 1586131200,
        "gmcode": "GM1724",
        "municipality_name": "Bergeijk",
        "moving_average_hospital": 0.7,
        "date_of_insertion_unix": 1605169739
      },
      {
        "date_of_report_unix": 1586217600,
        "gmcode": "GM1724",
        "municipality_name": "Bergeijk",
        "moving_average_hospital": 0.0,
        "date_of_insertion_unix": 1605169739
      },
      {
        "date_of_report_unix": 1586304000,
        "gmcode": "GM1724",
        "municipality_name": "Bergeijk",
        "moving_average_hospital": 0.0,
        "date_of_insertion_unix": 1605169739
      },
      {
        "date_of_report_unix": 1586390400,
        "gmcode": "GM1724",
        "municipality_name": "Bergeijk",
        "moving_average_hospital": 0.0,
        "date_of_insertion_unix": 1605169739
      },
      {
        "date_of_report_unix": 1586476800,
        "gmcode": "GM1724",
        "municipality_name": "Bergeijk",
        "moving_average_hospital": 0.0,
        "date_of_insertion_unix": 1605169739
      },
      {
        "date_of_report_unix": 1586563200,
        "gmcode": "GM1724",
        "municipality_name": "Bergeijk",
        "moving_average_hospital": 0.0,
        "date_of_insertion_unix": 1605169739
      },
      {
        "date_of_report_unix": 1586649600,
        "gmcode": "GM1724",
        "municipality_name": "Bergeijk",
        "moving_average_hospital": 0.3,
        "date_of_insertion_unix": 1605169739
      },
      {
        "date_of_report_unix": 1586736000,
        "gmcode": "GM1724",
        "municipality_name": "Bergeijk",
        "moving_average_hospital": 1.0,
        "date_of_insertion_unix": 1605169739
      },
      {
        "date_of_report_unix": 1586822400,
        "gmcode": "GM1724",
        "municipality_name": "Bergeijk",
        "moving_average_hospital": 1.3,
        "date_of_insertion_unix": 1605169739
      },
      {
        "date_of_report_unix": 1586908800,
        "gmcode": "GM1724",
        "municipality_name": "Bergeijk",
        "moving_average_hospital": 1.3,
        "date_of_insertion_unix": 1605169739
      },
      {
        "date_of_report_unix": 1586995200,
        "gmcode": "GM1724",
        "municipality_name": "Bergeijk",
        "moving_average_hospital": 0.7,
        "date_of_insertion_unix": 1605169739
      },
      {
        "date_of_report_unix": 1587081600,
        "gmcode": "GM1724",
        "municipality_name": "Bergeijk",
        "moving_average_hospital": 0.3,
        "date_of_insertion_unix": 1605169739
      },
      {
        "date_of_report_unix": 1587168000,
        "gmcode": "GM1724",
        "municipality_name": "Bergeijk",
        "moving_average_hospital": 0.0,
        "date_of_insertion_unix": 1605169739
      },
      {
        "date_of_report_unix": 1587254400,
        "gmcode": "GM1724",
        "municipality_name": "Bergeijk",
        "moving_average_hospital": 0.0,
        "date_of_insertion_unix": 1605169739
      },
      {
        "date_of_report_unix": 1587340800,
        "gmcode": "GM1724",
        "municipality_name": "Bergeijk",
        "moving_average_hospital": 0.0,
        "date_of_insertion_unix": 1605169739
      },
      {
        "date_of_report_unix": 1587427200,
        "gmcode": "GM1724",
        "municipality_name": "Bergeijk",
        "moving_average_hospital": 0.0,
        "date_of_insertion_unix": 1605169739
      },
      {
        "date_of_report_unix": 1587513600,
        "gmcode": "GM1724",
        "municipality_name": "Bergeijk",
        "moving_average_hospital": 0.0,
        "date_of_insertion_unix": 1605169739
      },
      {
        "date_of_report_unix": 1587600000,
        "gmcode": "GM1724",
        "municipality_name": "Bergeijk",
        "moving_average_hospital": 0.0,
        "date_of_insertion_unix": 1605169739
      },
      {
        "date_of_report_unix": 1587686400,
        "gmcode": "GM1724",
        "municipality_name": "Bergeijk",
        "moving_average_hospital": 0.0,
        "date_of_insertion_unix": 1605169739
      },
      {
        "date_of_report_unix": 1587772800,
        "gmcode": "GM1724",
        "municipality_name": "Bergeijk",
        "moving_average_hospital": 0.0,
        "date_of_insertion_unix": 1605169739
      },
      {
        "date_of_report_unix": 1587859200,
        "gmcode": "GM1724",
        "municipality_name": "Bergeijk",
        "moving_average_hospital": 0.0,
        "date_of_insertion_unix": 1605169739
      },
      {
        "date_of_report_unix": 1587945600,
        "gmcode": "GM1724",
        "municipality_name": "Bergeijk",
        "moving_average_hospital": 0.0,
        "date_of_insertion_unix": 1605169739
      },
      {
        "date_of_report_unix": 1588032000,
        "gmcode": "GM1724",
        "municipality_name": "Bergeijk",
        "moving_average_hospital": 0.7,
        "date_of_insertion_unix": 1605169739
      },
      {
        "date_of_report_unix": 1588118400,
        "gmcode": "GM1724",
        "municipality_name": "Bergeijk",
        "moving_average_hospital": 0.7,
        "date_of_insertion_unix": 1605169739
      },
      {
        "date_of_report_unix": 1588204800,
        "gmcode": "GM1724",
        "municipality_name": "Bergeijk",
        "moving_average_hospital": 0.7,
        "date_of_insertion_unix": 1605169739
      },
      {
